
version: '3.9'
services:
  db:
    container_name: dbchaty
    image: postgres
    restart: always
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=chatypwd
      - POSTGRES_USER=chaty
      - POSTGRES_DB=chaty
